export class Effects {
  constructor(game, explosionSheet, cloudSprite, smokeSprite){this.game=game;this.explosionSheet=explosionSheet;this.cloudSprite=cloudSprite;this.smokeSprite=smokeSprite;this.particles=[];this.explosions=[];this.clouds=[];this.smoke=[]}
  explode(x,y,amount=20,size=76){this.explosions.push({x,y,life:.58,max:.58,size});for(let i=0;i<amount;i++)this.particles.push({x,y,vx:(Math.random()-.5)*360,vy:(Math.random()-.5)*360,life:.72,max:.72,size:2+Math.random()*4,hue:25+Math.random()*35});for(let i=0;i<3;i++)this.smoke.push({x:x+(Math.random()-.5)*18,y:y+(Math.random()-.5)*18,vx:(Math.random()-.5)*18,vy:-18-Math.random()*18,life:1.2+Math.random()*.7,max:1.8,size:38+Math.random()*34,rot:Math.random()*Math.PI*2})}
  trail(x,y){if(Math.random()>.65)return;this.smoke.push({x:x+(Math.random()-.5)*5,y,vx:(Math.random()-.5)*8,vy:28+Math.random()*15,life:.55,max:.55,size:13+Math.random()*8,rot:Math.random()*Math.PI*2})}
  cloud(){this.clouds.push({x:Math.random()*this.game.width,y:-150,size:150+Math.random()*120,v:90+Math.random()*80,a:.55+Math.random()*.18,drift:(Math.random()-.5)*16})}
  update(dt){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=25*dt;p.life-=dt}for(const e of this.explosions)e.life-=dt;for(const c of this.clouds){c.y+=(this.game.speed*.42+c.v)*dt;c.x+=c.drift*dt}for(const s of this.smoke){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;s.rot+=dt*.25;s.size+=dt*9}this.particles=this.particles.filter(p=>p.life>0);this.explosions=this.explosions.filter(e=>e.life>0);this.clouds=this.clouds.filter(c=>c.y-c.size<this.game.height+150);this.smoke=this.smoke.filter(s=>s.life>0)}
  drawUnder(ctx){for(const s of this.smoke){const a=Math.max(0,s.life/s.max)*.5;ctx.save();ctx.globalAlpha=a;ctx.translate(s.x,s.y);ctx.rotate(s.rot);if(this.smokeSprite.complete)ctx.drawImage(this.smokeSprite,-s.size/2,-s.size*.34,s.size,s.size*.68);ctx.restore()}for(const p of this.particles){const a=p.life/p.max;ctx.save();ctx.fillStyle=`hsla(${p.hue},100%,58%,${a})`;ctx.shadowColor=`hsla(${p.hue},100%,50%,${a})`;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.8,p.size*a),0,Math.PI*2);ctx.fill();ctx.restore()}for(const e of this.explosions){const progress=1-e.life/e.max,frame=Math.min(7,Math.floor(progress*8));ctx.save();ctx.globalAlpha=Math.max(0,e.life/e.max);if(this.explosionSheet.complete)ctx.drawImage(this.explosionSheet,frame*192,0,192,192,e.x-e.size/2,e.y-e.size/2,e.size,e.size);ctx.restore()}}
  drawClouds(ctx){for(const c of this.clouds){ctx.save();ctx.globalAlpha=c.a;if(this.cloudSprite.complete)ctx.drawImage(this.cloudSprite,c.x-c.size/2,c.y-c.size*.34,c.size,c.size*.68);ctx.restore()}}
}
