const CFG={bird:{hp:1,points:20,size:34},airplane:{hp:3,points:90,size:55},helicopter:{hp:4,points:130,size:62},ufo:{hp:7,points:360,size:58},boat:{hp:3,points:85,size:58},submarine:{hp:5,points:190,size:58},truck:{hp:3,points:165,size:55}};
export class EnemySystem {
  constructor(game,sprites){this.game=game;this.sprites=sprites;this.items=[];this.trucks=[];this.timer=.7;this.lateral=3;this.water=4.5;this.bridge=8}
  reset(){this.items=[];this.trucks=[];this.timer=.7;this.lateral=3;this.water=4.5;this.bridge=8}
  make(type,x,y,movement="vertical"){const c=CFG[type];this.items.push({type,x,y,movement,hp:c.hp,points:c.points,size:c.size,vx:(Math.random()-.5)*90,phase:0,emerged:type!=="submarine",emerge:type==="submarine"?1+Math.random()*2.6:0,dead:false})}
  spawnVertical(){const y=-80,b=this.game.river.bounds(y,62),r=Math.random();const type=r>.97?"ufo":r>.80?"helicopter":r>.48?"airplane":"bird";this.make(type,b.left+Math.random()*(b.right-b.left),y)}
  spawnLateral(){const r=Math.random(),type=r>.93?"ufo":r>.7?"helicopter":r>.4?"airplane":"bird",left=Math.random()<.5;this.make(type,left?-100:this.game.width+100,this.game.height*(.18+Math.random()*.5),"lateral");const e=this.items.at(-1);e.vx=(left?1:-1)*(130+Math.random()*100)}
  spawnWater(){const y=-80,b=this.game.river.bounds(y,70),type=Math.random()<.68?"boat":"submarine";this.make(type,b.left+Math.random()*(b.right-b.left),y)}
  spawnTruck(){const y=-60,b=this.game.river.bounds(y);this.trucks.push({y,x:b.left,direction:1,speed:58+Math.random()*25,hp:3,points:165,dead:false})}
  update(dt){this.timer-=dt;this.lateral-=dt;this.water-=dt;this.bridge-=dt;if(this.timer<=0){this.spawnVertical();this.timer=.72+Math.random()*.7-Math.min(.28,this.game.time/100)}if(this.lateral<=0){this.spawnLateral();this.lateral=2.8+Math.random()*3.5}if(this.water<=0){this.spawnWater();this.water=4+Math.random()*4.5}if(this.bridge<=0){this.spawnTruck();this.bridge=8+Math.random()*5}
    for(const e of this.items){e.phase+=dt*7;if(e.movement==="lateral"){e.x+=e.vx*dt;e.y+=this.game.speed*.1*dt}else{e.y+=this.game.speed*dt;e.x+=e.vx*dt*.25}if(e.type==="submarine"&&!e.emerged){e.emerge-=dt;if(e.emerge<=0)e.emerged=true}}
    for(const t of this.trucks){t.y+=this.game.speed*dt;const b=this.game.river.bounds(t.y);t.x+=t.direction*t.speed*dt;if(t.x>b.right+35||t.x<b.left-35)t.direction*=-1}
    this.items=this.items.filter(e=>!e.dead&&e.y<this.game.height+120&&e.x>-180&&e.x<this.game.width+180);this.trucks=this.trucks.filter(t=>!t.dead&&t.y<this.game.height+100)}
  hitBullet(b){for(const e of this.items){if(e.dead||!e.emerged)continue;const d=(b.x-e.x)**2+(b.y-e.y)**2;if(d<(e.size*.5)**2){b.dead=true;e.hp--;if(e.hp<=0){e.dead=true;this.game.score+=e.points;this.game.effects.explode(e.x,e.y,e.type==="ufo"?32:20);this.game.audio.explosion();if(e.type==="helicopter"&&this.game.player.weapon<2){this.game.player.weapon=2;this.game.ui.message("TIRO DUPLO!")}if(e.type==="ufo"&&this.game.player.weapon<3){this.game.player.weapon=3;this.game.ui.message("TIRO TRIPLO!")}}return}}
    for(const t of this.trucks){if(t.dead)continue;if((b.x-t.x)**2+(b.y-t.y)**2<32**2){b.dead=true;t.hp--;if(t.hp<=0){t.dead=true;this.game.score+=t.points;this.game.player.weapon=Math.min(3,this.game.player.weapon+1);this.game.effects.explode(t.x,t.y,24);this.game.ui.message(`CAMINHÃO +${t.points}`)}return}}
  }
  collidePlayer(){const p=this.game.player;for(const e of this.items){if(e.dead||!e.emerged)continue;if((p.x-e.x)**2+(p.y-e.y)**2<(18+e.size*.42)**2)p.damage(e.type==="ufo"?28:e.type==="submarine"?26:18)}}
  draw(ctx){for(const e of this.items){if(e.type==="submarine"&&!e.emerged){ctx.save();ctx.globalAlpha=.22;ctx.fillStyle="#1d4052";ctx.beginPath();ctx.ellipse(e.x,e.y,28,9,0,0,Math.PI*2);ctx.fill();ctx.restore();continue}const img=this.sprites[e.type]||this.sprites.airplane;if(!img?.complete)continue;ctx.save();ctx.translate(e.x,e.y);if(e.movement==="lateral")ctx.rotate(e.vx>0?Math.PI/2:-Math.PI/2);ctx.shadowColor="rgba(0,0,0,.35)";ctx.shadowBlur=9;ctx.shadowOffsetY=6;ctx.drawImage(img,-e.size/2,-e.size/2,e.size,e.size);ctx.restore()}
    for(const t of this.trucks){const img=this.sprites.truck;if(!img?.complete)continue;ctx.save();ctx.translate(t.x,t.y);if(t.direction<0)ctx.scale(-1,1);ctx.drawImage(img,-38,-22,76,44);ctx.restore()}}
}
