const c=document.querySelector("#game"),x=c.getContext("2d");const load=n=>{let i=new Image;i.src="./assets/sprites/"+n;return i};const I={player:load("player.png"),enemy:load("enemy.png"),heli:load("heli.png"),boat:load("boat.png"),sub:load("sub.png"),truck:load("truck.png"),bridge:load("bridge.png"),boss:load("boss.png"),expl:load("explosion.png"),bank:load("bank.png"),water:[0,1,2,3].map(n=>load("water"+n+".png")),fuel:load("fuel.png"),shield:load("shield.png"),repair:load("repair.png"),bomb:load("bomb.png"),coin:load("coin.png"),life:load("life.png"),weapon:load("weapon.png")};let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),run=false,pause=false,last=0,t=0,score=0,stage=1,speed=190,fire=false,mfire=false,fireT=0,spawnT=0,bridgeT=5,boss=null,frame=0,shake=0,record=+localStorage.srr4||0,keys=new Set,joy={x:0,y:0},enemies=[],bullets=[],items=[],bridges=[],trucks=[],explosions=[];const p={x:W/2,y:H*.78,tx:W/2,ty:H*.78,fuel:100,lives:3,shield:0,weapon:1,bombs:0,inv:0};function resize(){W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D}resize();addEventListener("resize",resize);
function center(y){let n=y/H,w=n*2.6+t*.16;return W*.5+Math.sin(w)*W*.18+Math.sin(w*1.8)*W*.04}function half(y){let n=y/H,w=n*3.4+t*.11;return Math.max(W*.17,W*.31+Math.sin(w)*W*.035)}function bounds(y,m=0){let q=center(y),h=Math.max(42,half(y)-m);return{l:q-h,r:q+h}}
const E={hud:document.querySelector("#hud"),fuel:document.querySelector("#fuel"),lives:document.querySelector("#lives"),shield:document.querySelector("#shield"),weapon:document.querySelector("#weapon"),bombs:document.querySelector("#bombs"),score:document.querySelector("#score"),menu:document.querySelector("#menu"),over:document.querySelector("#over"),paused:document.querySelector("#paused"),msg:document.querySelector("#msg"),stage:document.querySelector("#stage"),joy:document.querySelector("#joy")};for(let i=0;i<12;i++)E.fuel.appendChild(document.createElement("i"));function ui(){let on=Math.ceil(Math.max(0,p.fuel)/100*12);[...E.fuel.children].forEach((q,i)=>{q.className=i<on?"on "+(i<3?"r":i<7?"y":"g"):""});E.lives.textContent=p.lives;E.shield.textContent=p.shield;E.weapon.textContent=p.weapon;E.bombs.textContent=p.bombs;E.score.textContent=Math.floor(score)}function msg(s){E.msg.textContent=s;E.msg.style.opacity=1;setTimeout(()=>E.msg.style.opacity=0,800)}function stageMsg(s){E.stage.textContent=s;setTimeout(()=>E.stage.textContent="",1400)}
function reset(){t=score=0;stage=1;speed=190;spawnT=0;bridgeT=5;boss=null;enemies=[];bullets=[];items=[];bridges=[];trucks=[];explosions=[];Object.assign(p,{x:W/2,y:H*.78,tx:W/2,ty:H*.78,fuel:100,lives:3,shield:0,weapon:1,bombs:0,inv:0});run=true;pause=false;E.menu.classList.add("hidden");E.over.classList.add("hidden");E.hud.classList.remove("hidden");E.joy.classList.remove("hidden");stageMsg("FASE 1");ui()}
function spawnEnemy(){let b=bounds(-70,95),r=Math.random(),type=r>.75?"heli":r>.45?"enemy":r>.22?"boat":"sub";enemies.push({type,x:b.l+Math.random()*(b.r-b.l),y:-70,hp:type==="heli"?4:type==="sub"?5:type==="boat"?3:2,size:type==="heli"?60:56})}function spawnItem(xx=null,yy=-60){let b=bounds(yy,105),r=Math.random(),type=r<.25?"fuel":r<.4?"shield":r<.55?"repair":r<.68?"bomb":r<.82?"coin":r<.92?"weapon":"life";items.push({type,x:xx??b.l+30+Math.random()*Math.max(1,b.r-b.l-60),y:yy,ph:Math.random()*6.28})}function spawnBridge(){let br={y:-60};bridges.push(br);setTimeout(()=>trucks.push({b:br,x:center(br.y)-half(br.y)+30,dir:1,hp:3}),250)}
function hitPlayer(n){if(p.inv>0)return;if(p.shield){p.shield--;p.inv=.6;msg("ESCUDO");return}p.fuel-=n;p.inv=.8;explosions.push({x:p.x,y:p.y,l:.7});if(p.fuel<=0){p.lives--;if(p.lives<=0){run=false;E.over.classList.remove("hidden");document.querySelector("#final").textContent="PONTOS "+Math.floor(score);if(score>record){record=Math.floor(score);localStorage.srr4=record}}else{p.fuel=100;p.x=p.tx=W/2;p.y=p.ty=H*.78;p.inv=2}}}
function update(dt){if(!run||pause)return;t+=dt;score+=dt*10;speed=Math.min(300,190+stage*12+t*.7);p.fuel-=dt*(2.5+stage*.2);p.inv=Math.max(0,p.inv-dt);let dx=joy.x,dy=joy.y;if(keys.has("ArrowLeft")||keys.has("KeyA"))dx--;if(keys.has("ArrowRight")||keys.has("KeyD"))dx++;if(keys.has("ArrowUp")||keys.has("KeyW"))dy--;if(keys.has("ArrowDown")||keys.has("KeyS"))dy++;if(dx||dy){let m=Math.hypot(dx,dy)||1;p.tx+=dx/m*320*dt;p.ty+=dy/m*320*dt}p.ty=Math.max(90,Math.min(H-60,p.ty));let b=bounds(p.y,48);p.tx=Math.max(b.l,Math.min(b.r,p.tx));p.x+=(p.tx-p.x)*Math.min(1,dt*11);p.y+=(p.ty-p.y)*Math.min(1,dt*11);b=bounds(p.y,40);if(p.x<b.l){p.x=b.l;hitPlayer(10)}if(p.x>b.r){p.x=b.r;hitPlayer(10)}
fireT-=dt;if((fire||mfire)&&fireT<=0){let os=p.weapon===1?[0]:p.weapon===2?[-10,10]:[-16,0,16];os.forEach(o=>bullets.push({x:p.x+o,y:p.y-35,pow:Math.min(3,1+Math.floor((p.weapon-1)/2))}));fireT=Math.max(.08,.18-p.weapon*.018)}spawnT-=dt;if(spawnT<=0&&!boss){spawnEnemy();spawnT=.65+Math.random()*.7}bridgeT-=dt;if(bridgeT<=0&&!boss){spawnBridge();bridgeT=9+Math.random()*6}if(t>38&&!boss){boss={x:W/2,y:-120,hp:110+stage*20,max:110+stage*20,ph:0};stageMsg("CHEFE")}
bullets.forEach(q=>q.y-=680*dt);enemies.forEach(e=>e.y+=speed*dt);bridges.forEach(q=>q.y+=speed*dt);trucks.forEach(q=>{q.y=q.b.y;let cc=center(q.y),hh=half(q.y);q.x+=q.dir*75*dt;if(q.x>cc+hh+20||q.x<cc-hh-20)q.dir*=-1});items.forEach(q=>{q.y+=speed*dt;q.ph+=dt*4;let s=bounds(q.y,100);q.x=Math.max(s.l+25,Math.min(s.r-25,q.x))});explosions.forEach(q=>q.l-=dt);
bullets.forEach(q=>{
  enemies.forEach(e=>{
    if(!q.d&&!e.d&&(q.x-e.x)**2+(q.y-e.y)**2<(e.size*.42)**2){
      q.d=1;e.hp-=q.pow;
      if(e.hp<=0){e.d=1;score+=100;explosions.push({x:e.x,y:e.y,l:.7});if(Math.random()<.25)spawnItem(e.x,e.y)}
    }
  });
  trucks.forEach(e=>{
    if(!q.d&&!e.d&&(q.x-e.x)**2+(q.y-e.y)**2<30**2){
      q.d=1;e.hp-=q.pow;
      if(e.hp<=0){e.d=1;p.weapon=Math.min(5,p.weapon+1);msg("ARMA "+p.weapon);explosions.push({x:e.x,y:e.y,l:.7})}
    }
  });
  if(boss&&!q.d&&Math.abs(q.x-boss.x)<70&&Math.abs(q.y-boss.y)<65){
    q.d=1;boss.hp-=q.pow;
    if(boss.hp<=0){score+=5000;explosions.push({x:boss.x,y:boss.y,l:.7});boss=null;stage++;t=0;stageMsg("FASE "+stage)}
  }
});
enemies.forEach(e=>{if(!e.d&&(p.x-e.x)**2+(p.y-e.y)**2<(24+e.size*.35)**2)hitPlayer(18)});
if(boss){boss.ph+=dt;if(boss.y<140)boss.y+=80*dt;else boss.x=W/2+Math.sin(boss.ph)*W*.22}
items.forEach(q=>{if(!q.d&&(p.x-q.x)**2+(p.y-q.y)**2<40**2){q.d=1;if(q.type==="fuel")p.fuel=Math.min(100,p.fuel+40);if(q.type==="shield")p.shield=Math.min(3,p.shield+1);if(q.type==="repair")p.fuel=Math.min(100,p.fuel+22);if(q.type==="bomb")p.bombs=Math.min(5,p.bombs+1);if(q.type==="coin")score+=100;if(q.type==="weapon")p.weapon=Math.min(5,p.weapon+1);if(q.type==="life")p.lives=Math.min(5,p.lives+1);msg(q.type.toUpperCase())}});bullets=bullets.filter(q=>!q.d&&q.y>-50);enemies=enemies.filter(e=>!e.d&&e.y<H+80);items=items.filter(q=>!q.d&&q.y<H+60);bridges=bridges.filter(q=>q.y<H+70);trucks=trucks.filter(q=>!q.d&&q.y<H+70);explosions=explosions.filter(q=>q.l>0);ui()}
function draw(){x.setTransform(D,0,0,D,0,0);x.clearRect(0,0,W,H);x.fillStyle="#245f36";x.fillRect(0,0,W,H);x.beginPath();for(let y=-40;y<H+40;y+=14){let cc=center(y),hh=half(y);y===-40?x.moveTo(cc-hh,y):x.lineTo(cc-hh,y)}for(let y=H+40;y>=-40;y-=14){let cc=center(y),hh=half(y);x.lineTo(cc+hh,y)}x.closePath();x.fillStyle="#1a6da9";x.fill();x.save();x.clip();let wi=I.water[Math.floor(t*7)%4];if(wi.complete){let pat=x.createPattern(wi,"repeat");x.fillStyle=pat;x.fillRect(0,0,W,H)}x.restore();bridges.forEach(q=>{let cc=center(q.y),hh=half(q.y);x.drawImage(I.bridge,cc-hh-10,q.y-20,hh*2+20,40)});trucks.forEach(q=>x.drawImage(I.truck,q.x-36,q.y-24,72,48));enemies.forEach(e=>x.drawImage(I[e.type],e.x-e.size/2,e.y-e.size/2,e.size,e.size));items.forEach(q=>x.drawImage(I[q.type],q.x-25,q.y+Math.sin(q.ph)*3-25,50,50));bullets.forEach(q=>{x.fillStyle=q.pow>=3?"#5ce7ff":q.pow===2?"#ffb13c":"#ff5b4d";x.fillRect(q.x-(2+q.pow),q.y,4+q.pow*2,18+q.pow*3)});if(boss){x.drawImage(I.boss,boss.x-96,boss.y-96,192,192);x.fillStyle="#111";x.fillRect(W/2-90,70,180,12);x.fillStyle="#e5524b";x.fillRect(W/2-88,72,176*boss.hp/boss.max,8)}explosions.forEach(q=>{let f=Math.min(11,Math.floor((1-q.l/.7)*12));x.drawImage(I.expl,f*128,0,128,128,q.x-50,q.y-50,100,100)});x.fillStyle="#0006";x.beginPath();x.ellipse(p.x,p.y+32,40,10,0,0,6.28);x.fill();x.drawImage(I.player,p.x-48,p.y-48,96,96)}
function loop(n){let dt=Math.min(.04,Math.max(0,(n-(last||n))/1000));last=n;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
document.querySelector("#play").onclick=reset;document.querySelector("#restart").onclick=reset;document.querySelector("#pause").onclick=()=>{pause=!pause;E.paused.classList.toggle("hidden",!pause)};document.querySelector("#resume").onclick=()=>{pause=false;E.paused.classList.add("hidden")};addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space")fire=true});addEventListener("keyup",e=>{keys.delete(e.code);if(e.code==="Space")fire=false});document.querySelector("#fire").onpointerdown=()=>mfire=true;document.querySelector("#fire").onpointerup=()=>mfire=false;let J=document.querySelector("#joy"),K=document.querySelector("#knob"),active=false;function jm(e){let r=J.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy)||1;if(m>max){dx=dx/m*max;dy=dy/m*max}joy.x=dx/max;joy.y=dy/max;K.style.transform=`translate(${dx}px,${dy}px)`}J.onpointerdown=e=>{active=true;jm(e)};J.onpointermove=e=>{if(active)jm(e)};J.onpointerup=J.onpointercancel=()=>{active=false;joy.x=joy.y=0;K.style.transform="translate(0,0)"};